- restConfiguration:
    apiComponent: openapi
    apiContextPath: api-doc
    clientRequestValidation: false
    inlineRoutes: true
- rest:
    id: rest-1765
    apiDocs: true
    openApi:
      missingOperation: ignore
      specification: greetings.json
- route:
    id: route-1713
    from:
      id: from-7247
      uri: direct:greetings
      steps:
        - setBody:
            simple: Hello from Miguel
        - log:
            id: log-1795
            message: ${body}
