apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kamelk-openapi-greetings
    app.kubernetes.io/runtime: camel
  name: kamelk-openapi-greetings
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kamelk-openapi-greetings
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kamelk-openapi-greetings
    spec:
      containers:
      - image: kamelk-openapi-greetings:1.0-SNAPSHOT
        name: kamelk-openapi-greetings
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
