apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kamelk-openapi-greetings
    app.kubernetes.io/runtime: camel
  name: kamelk-openapi-greetings
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: kamelk-openapi-greetings
  type: ClusterIP
